### ISSUE TITLE
WS-RM doesn't allow overwriting the endpoint URL if the scheme (http/https) in offline wsdl is different from the scheme is the actual endpoint URL.

### ISSUE THREAD

**Issue by avi5kdonrh** [quarkiverse/quarkus-cxf#1061]
Reproducer and ReadME.

https://github.com/avi5kdonrh/quarkus-cxf-reproducer/tree/master

Explanation:

If I use an offline/local WSDL while creating the service:
```
Service service = Service
                .create("/local/wsdl/service.wsdl",
                        serviceName);
```

And the WSDL <soap:address location=> has the url starting with https, I cannot overwrite it with an http URL while building the soap client.

For example, doing the following doesn't work:

`BindingProvider bindingProvider = (BindingProvider) proxy; bindingProvider.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY,"http://localhost:8081/cxf/WsrmHelloServicePort");`

But, if I set the ENDPOINT_ADDRESS_PROPERTY to an https URL, it works fine.

In a  nutshell: 
Offline WSDL --> https; Client URL: http -----> Doesn't work
Offline WSDL --> http; Client URL: https -----> Doesn't work
Offline WSDL --> https; Client URL: https -----> Works
Offline WSDL --> http; Client URL: http -----> Works

**Comment by ppalaga** [comment]
Apart that WS-RM is [known not to work](https://github.com/quarkiverse/quarkus-cxf/issues/627), it sounds like what you find not working correctly is the client code in `WsReliableMessagingTest`, right? If so, I do not see anything Quarkus CXF specific there, so it it would rather be an issue you should report against [Apache CXF](https://issues.apache.org/jira/browse/CXF).

It could be seen as Quarkus CXF specific, if the client lived in the application (rather than in the test code) and you configured it via application.properties. You can wrap the client in a REST service for the sake of testing like we explain [here](https://docs.quarkiverse.io/quarkus-cxf/dev/user-guide/first-soap-client.html#_using_sei_as_a_client). 
Please let me know if setting the `quarkus.cxf.client.yourClient.client-endpoint-url` in application.properties does not have the desired effect.

**Comment by ppalaga** [comment]
> Please let me know if setting the quarkus.cxf.client.yourClient.client-endpoint-url in application.properties does not have the desired effect.

It does not either. I am investigating.

**Comment by ppalaga** [comment]
Indeed, this only does not work when the client is first created from the WSDL containing fake address and then the correct address is set via `Message.ENDPOINT_ADDRESS` on the client's request context. The wrong address stays unchanged in `client.getEndpoint().getEndpointInfo().getAddress()`. As a result of that, `org.apache.cxf.endpoint.AbstractConduitSelector.findCompatibleConduit(Message)` thinks there is no ready to use HTTPConduit for the HTTPS protocol taken from the fake address. Then a new conduit is created and the wrong address is taken from `EndpointInfo.getAddress()` for sending the createSequence request. 

Here is how the issue can be worked around from the client side: https://github.com/avi5kdonrh/quarkus-cxf-reproducer/pull/2/files#diff-cdb808b7c9277562297486ef9f34de4a678f4db7ea4bffecaae5fe74a0816c46R48-R49

**Comment by ppalaga** [comment]
@ffang could you please have a look at the above reproducer and the results of my investigation and utter your opinion whether it works as designed or whether it is a bug? 

I thought a fix like this https://github.com/ppalaga/cxf/commit/bde87294ce9ed5d276eec9da4166ec501ba21f06#diff-1fd3e411b74532c742a06620a998493a71f17548bc077003036e49c0833ec9d9R490-R493 could solve the issue, but it unfortunately breaks the `correct()` test

**Comment by ppalaga** [comment]
@avi5kdonrh is the above explanation by @ffang sufficient for you?

**Comment by jochenr** [comment]
the explanation is good and reasonable.

But IMHO there are three ways of overriding the endpoint URL mentioned in the CXF dos:
https://cxf.apache.org/docs/client-http-transport-including-ssl-support.html#ClientHTTPTransport(includingSSLsupport)-Howtooverridetheserviceaddress?

..and so all three should/have to work

And actually setting ENDPOINT_ADDRESS_PROPERTY  worked well for several years from CXF 2.7.x until 4.0.??, but not in 4.0.2 any more.

Also the solution 
```
service.addPort(portName, "http://schemas.xmlsoap.org/soap/", "http://the/new/url/myService");
```
does not work, if you combine WS-RM with WS-Security and try to use the HTTPConduit.
See example: 
https://github.com/jochenr/my-camel-quarkus-projects/blob/613ae6ce269e7f169272663f877814b8e3da05f4/camel-quarkus-cxf-soap-wssecurity-wsrm/quarkus-root/src/test/java/de/jochenr/integration/contact/ContactTest.java#L83

**Comment by ffang** [comment]
> the explanation is good and reasonable.
> 
> But IMHO there are three ways of overriding the endpoint URL mentioned in the CXF dos: https://cxf.apache.org/docs/client-http-transport-including-ssl-support.html#ClientHTTPTransport(includingSSLsupport)-Howtooverridetheserviceaddress?
> 
> ..and so all three should/have to work
> 
> And actually setting ENDPOINT_ADDRESS_PROPERTY worked well for several years from CXF 2.7.x until 4.0.??, but not in 4.0.2 any more.
> 

I believe this is caused by new in-JDK http-client used recently in CXF for CXF conduit(CXF client), previously it was URLConnection based CXF conduit. And hence the current behaviour actually is more align with the JAXWS spec 
```
/**
     * Standard property: Target service endpoint address. The
     * URI scheme for the endpoint address specification MUST
     * correspond to the protocol/transport binding for the
     * binding in use.
     * <p>Type: {@code java.lang.String}
     **/
    String ENDPOINT_ADDRESS_PROPERTY =
            "jakarta.xml.ws.service.endpoint.address";
```
So I don't see this is a regression but an improvement.
> Also the solution
> 
> ```
> service.addPort(portName, "http://schemas.xmlsoap.org/soap/", "http://the/new/url/myService");
> ```
> 
> does not work, if you combine WS-RM with WS-Security and try to use the HTTPConduit. See example: https://github.com/jochenr/my-camel-quarkus-projects/blob/613ae6ce269e7f169272663f877814b8e3da05f4/camel-quarkus-cxf-soap-wssecurity-wsrm/quarkus-root/src/test/java/de/jochenr/integration/contact/ContactTest.java#L83

Should be addressed already with latest build.

Thanks!

**Comment by ppalaga** [comment]
@avi5kdonrh @jochenr I think we can close this one. Please feel free to reopen if needed.

**Comment by jochenr** [comment]
Hi @ppalaga,

closing this is/was correct.
"no fix/won't fix" is wrong, because it was fixed. My old code is working again, since I use a fixed version of CXF (4.0.2 was not a good version of CXF)....

Thank you

**Comment by ppalaga** [comment]
> "no fix/won't fix" is wrong

Well, it is just a marker that this issue cannot be mapped to any commit in Quarkus CXF git repo. It's more like "we have not fixed", but there still might be a fix in a dependency. Sorry for the confusion
